CREATE TABLE ADMINISTRADORES
(
ID_USUARIO INTEGER NOT NULL,
LIST_TAREAS VARCHAR(100) NOT NULL,
CEDULA INTEGER NOT NULL,
INSTITUTO VARCHAR(30) NOT NULL
);

ALTER TABLE ADMINISTRADORES
ADD
(
CONSTRAINT PK_CEDULA_ADMINISTRADOR PRIMARY KEY (CEDULA),
CONSTRAINT FK_ID_USUARIO_ADM FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
ON DELETE CASCADE,
CONSTRAINT UK_ID_USUARIO_ADM UNIQUE (ID_USUARIO)
);
