CREATE TABLE ADMINISTRADORES
(
ID_ADMINISTRADOR INTEGER NOT NULL,
LISTA_DE_TAREAS_AD VARCHAR(100) NOT NULL,
CEDULA INTEGER NOT NULL,
INSTITUTO VARCHAR(30) NOT NULL
);

ALTER TABLE ADMINISTRADORES
ADD
(
CONSTRAINT PK_ID_ADMINISTRADOR PRIMARY KEY (ID_ADMINISTRADOR),
CONSTRAINT UK_ADMINISTRADOR_CEDULA UNIQUE (CEDULA)
);