CREATE TABLE ADMINISTRADORES
(
ID_USUARIO INTEGER NOT NULL,
LIST_TAREAS VARCHAR(100) NOT NULL,
CEDULA INTEGER NOT NULL,
INSTITUTO VARCHAR(30) NOT NULL
);

ALTER TABLE ADMINISTRADORES
ADD
(
CONSTRAINT PK_CEDULA PRIMARY KEY (CEDULA),
CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIOS)
);
