CREATE TABLE ROLES
(
ID_ROL INTEGER NOT NULL,
ID_USUARIO INTEGER NOT NULL,
ID_COMUN INTEGER NOT NULL,
ID_EXPERTO INTEGER NOT NULL,
ID_ADMINISTRADOR INTEGER NOT NULL
);



ALTER TABLE ROLES
ADD
(
CONSTRAINT PK_ID_ROL PRIMARY KEY (ID_ROL),
CONSTRAINT FK_ROL_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO),
CONSTRAINT FK_ROL_ID_COMUN FOREIGN KEY (ID_COMUN) REFERENCES COMUNES (ID_COMUN),
CONSTRAINT FK_ROL_ID_EXPERTO FOREIGN KEY (ID_EXPERTO) REFERENCES EXPERTOS (ID_EXPERTO),
CONSTRAINT FK_ROL_ID_ADMINISTRADOR FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES ADMINISTRADORES (ID_ADMINISTRADOR)
);