--------------------------------------------------------
-- Archivo creado  - viernes-septiembre-11-2020   
--------------------------------------------------------
DROP TABLE "PDT"."ADMINISTRADORES" cascade constraints;
DROP TABLE "PDT"."CASILLAS" cascade constraints;
DROP TABLE "PDT"."COMUNES" cascade constraints;
DROP TABLE "PDT"."EXPERTOS" cascade constraints;
DROP TABLE "PDT"."FORMULARIOS" cascade constraints;
DROP TABLE "PDT"."USUARIOS" cascade constraints;
--------------------------------------------------------
--  DDL for Table ADMINISTRADORES
--------------------------------------------------------

  CREATE TABLE "PDT"."ADMINISTRADORES" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"LIST_TAREAS" VARCHAR2(100 BYTE), 
	"CEDULA" NUMBER(*,0), 
	"INSTITUTO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CASILLAS
--------------------------------------------------------

  CREATE TABLE "PDT"."CASILLAS" 
   (	"ID_CASILLA" NUMBER(*,0), 
	"PARAMETRO" VARCHAR2(30 BYTE), 
	"UNI_MEDIDA" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(40 BYTE), 
	"TIPO_INPUT" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMUNES
--------------------------------------------------------

  CREATE TABLE "PDT"."COMUNES" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"LIST_TAREAS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXPERTOS
--------------------------------------------------------

  CREATE TABLE "PDT"."EXPERTOS" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"LIS_TAREAS" VARCHAR2(100 BYTE), 
	"CEDULA" NUMBER(*,0), 
	"PROFESION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORMULARIOS
--------------------------------------------------------

  CREATE TABLE "PDT"."FORMULARIOS" 
   (	"ID_FORMULARIO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"MET_MUESTREO" VARCHAR2(20 BYTE), 
	"EQUIPAMIENTO" VARCHAR2(100 BYTE), 
	"NOM_FORMULARIO" VARCHAR2(20 BYTE), 
	"RESUMEN" VARCHAR2(300 BYTE), 
	"DEPARTAMENTO" VARCHAR2(20 BYTE), 
	"FECHA" DATE, 
	"ZONA" VARCHAR2(20 BYTE), 
	"TIP_MUESTREO" VARCHAR2(20 BYTE), 
	"GEOPUNTO" LONG, 
	"LOCALIDAD" VARCHAR2(30 BYTE), 
	"EST_MUESTREO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "PDT"."USUARIOS" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE), 
	"NOMB_USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASENIA" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into PDT.ADMINISTRADORES
SET DEFINE OFF;
REM INSERTING into PDT.CASILLAS
SET DEFINE OFF;
REM INSERTING into PDT.COMUNES
SET DEFINE OFF;
REM INSERTING into PDT.EXPERTOS
SET DEFINE OFF;
REM INSERTING into PDT.FORMULARIOS
SET DEFINE OFF;
REM INSERTING into PDT.USUARIOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ID_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_ID_USUARIO" ON "PDT"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USUARIO_NOMB
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."UK_USUARIO_NOMB" ON "PDT"."USUARIOS" ("NOMB_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USUARIO_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."UK_USUARIO_EMAIL" ON "PDT"."USUARIOS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_FORMULARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_ID_FORMULARIO" ON "PDT"."FORMULARIOS" ("ID_FORMULARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_FECHA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."UK_FECHA" ON "PDT"."FORMULARIOS" ("FECHA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CEDULA_ADMINISTRADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_CEDULA_ADMINISTRADOR" ON "PDT"."ADMINISTRADORES" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ID_USUARIO_ADM
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."UK_ID_USUARIO_ADM" ON "PDT"."ADMINISTRADORES" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CASILLAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_CASILLAS" ON "PDT"."CASILLAS" ("ID_CASILLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ID_USUARIO_COMUNES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."UK_ID_USUARIO_COMUNES" ON "PDT"."COMUNES" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EXPERTO_CEDULA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."PK_EXPERTO_CEDULA" ON "PDT"."EXPERTOS" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_EXPERTO_ID_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDT"."UK_EXPERTO_ID_USUARIO" ON "PDT"."EXPERTOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMUNES
--------------------------------------------------------

  ALTER TABLE "PDT"."COMUNES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."COMUNES" MODIFY ("LIST_TAREAS" NOT NULL ENABLE);
  ALTER TABLE "PDT"."COMUNES" ADD CONSTRAINT "UK_ID_USUARIO_COMUNES" UNIQUE ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMINISTRADORES
--------------------------------------------------------

  ALTER TABLE "PDT"."ADMINISTRADORES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."ADMINISTRADORES" MODIFY ("LIST_TAREAS" NOT NULL ENABLE);
  ALTER TABLE "PDT"."ADMINISTRADORES" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "PDT"."ADMINISTRADORES" MODIFY ("INSTITUTO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."ADMINISTRADORES" ADD CONSTRAINT "PK_CEDULA_ADMINISTRADOR" PRIMARY KEY ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PDT"."ADMINISTRADORES" ADD CONSTRAINT "UK_ID_USUARIO_ADM" UNIQUE ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXPERTOS
--------------------------------------------------------

  ALTER TABLE "PDT"."EXPERTOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."EXPERTOS" MODIFY ("LIS_TAREAS" NOT NULL ENABLE);
  ALTER TABLE "PDT"."EXPERTOS" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "PDT"."EXPERTOS" MODIFY ("PROFESION" NOT NULL ENABLE);
  ALTER TABLE "PDT"."EXPERTOS" ADD CONSTRAINT "PK_EXPERTO_CEDULA" PRIMARY KEY ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PDT"."EXPERTOS" ADD CONSTRAINT "UK_EXPERTO_ID_USUARIO" UNIQUE ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORMULARIOS
--------------------------------------------------------

  ALTER TABLE "PDT"."FORMULARIOS" MODIFY ("ID_FORMULARIO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."FORMULARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."FORMULARIOS" MODIFY ("MET_MUESTREO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."FORMULARIOS" MODIFY ("NOM_FORMULARIO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."FORMULARIOS" MODIFY ("DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."FORMULARIOS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "PDT"."FORMULARIOS" ADD CONSTRAINT "PK_ID_FORMULARIO" PRIMARY KEY ("ID_FORMULARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PDT"."FORMULARIOS" ADD CONSTRAINT "UK_FECHA" UNIQUE ("FECHA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CASILLAS
--------------------------------------------------------

  ALTER TABLE "PDT"."CASILLAS" MODIFY ("ID_CASILLA" NOT NULL ENABLE);
  ALTER TABLE "PDT"."CASILLAS" MODIFY ("PARAMETRO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."CASILLAS" MODIFY ("UNI_MEDIDA" NOT NULL ENABLE);
  ALTER TABLE "PDT"."CASILLAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PDT"."CASILLAS" MODIFY ("TIPO_INPUT" NOT NULL ENABLE);
  ALTER TABLE "PDT"."CASILLAS" ADD CONSTRAINT "PK_CASILLAS" PRIMARY KEY ("ID_CASILLA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "PDT"."USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PDT"."USUARIOS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."USUARIOS" MODIFY ("NOMB_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PDT"."USUARIOS" MODIFY ("CONTRASENIA" NOT NULL ENABLE);
  ALTER TABLE "PDT"."USUARIOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PDT"."USUARIOS" ADD CONSTRAINT "PK_ID_USUARIO" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PDT"."USUARIOS" ADD CONSTRAINT "UK_USUARIO_NOMB" UNIQUE ("NOMB_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PDT"."USUARIOS" ADD CONSTRAINT "UK_USUARIO_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADMINISTRADORES
--------------------------------------------------------

  ALTER TABLE "PDT"."ADMINISTRADORES" ADD CONSTRAINT "FK_ID_USUARIO_ADM" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PDT"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMUNES
--------------------------------------------------------

  ALTER TABLE "PDT"."COMUNES" ADD CONSTRAINT "FK_ID_USUARIO_COMUNES" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PDT"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXPERTOS
--------------------------------------------------------

  ALTER TABLE "PDT"."EXPERTOS" ADD CONSTRAINT "FK_ID_USUARIO_EXPERTO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PDT"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORMULARIOS
--------------------------------------------------------

  ALTER TABLE "PDT"."FORMULARIOS" ADD CONSTRAINT "FK_ID_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PDT"."USUARIOS" ("ID_USUARIO") ENABLE;
